### ISSUE TITLE
Compare self-calib and absolute calibration of the flow measurement

### ISSUE THREAD

**Issue by cocov** [hev-sw/hev-analysis#1]
# Explanation of the issue

The flow measurement in  HEV is done by measuring the differential pressure on the two side of a restriction.
In the setup the piece with restriction (I think that's how it work) is placed on the mouthpiece https://www.hamilton-medical.com/fr/Products/Accessories-and-Consumables/E-catalog/Detail~281637~Flow-sensor~7e01c9fd-4af9-48ed-a6bf-89f5beed4771~.html , and two tube runs up to the differential pressure sensor https://docs.rs-online.com/7d77/0900766b81568899.pdf

In https://lblogbook.cern.ch/HEV/28 Oscar measured the flow with an independent flowmeter and the volage recorded by the dp sensor. That should give the absolute calibration.

In https://lblogbook.cern.ch/HEV/26 and https://lblogbook.cern.ch/HEV/32 I took data from HEV (the entry "P_diff (Scaled) 1" is the differential pressure), and at the same time data from the test chest that have a flow meter integrated to it (the entry "Flow " in mL/s). What you can see is the the calibration constant between flow and dp is different between positive and negative flow, which might indicate a leak. 

# Task

1. Use Oscar measurement to apply it to the data_hev["P_diff (Scaled) 1"] data and compare the flow with the flow measured by the testchest data_tc["Flow "]  (look at the spline interpolation if you want to access the values at any arbitrary time, example in non_linear_calib.py but will become a tool)

2. Find a way to evaluate the leak amount, correct for it and then evaluate the volume

# Priority

URGENT

**Comment by cocov** [comment]
Might be relavant at one point: most units are mbar for pressure, mL for volume. The flow in testchest is in mL/min

**Comment by gcavalle** [comment]
At https://github.com/hev-sw/hev-analysis/blob/gcavalle_flowCalibration/flowComparison.png there is a plot showing the comparison between the flow as measured by the testchest (black) and the flow computed from an interpolation to the dp sensor calibration (red). According to https://lblogbook.cern.ch/HEV/28 the flow from the flowmeter is in NL/h, but it looks the two curves are matching quite well. The code is in gcavalle_flowCalibration in absolute_calibration.py. I wanted to plot the two flows one against the other but I am struggling with the different number of points in the hev and tc datasets, so for the moment I've only pushed this.

**Comment by cocov** [comment]
Great! The remaining difference could be due to a leak (the red curve tend to undershoot in the negative flow, but if there is a leak the exhale volume would indeed be less than the inhale one), I should go at one point tomorrow to check the setup. At the beginning of the inhale when the flow goes up quickly, there the flow from dp is systematically lower do you think it could also be due to some limitation in the sensitivity of the sensor to transient? I don't know it looks a bit like if the peak was smeared out.
I don't know what the NL means exactly. Well it is "Normal Litter" but I am not sure of the meaning. I remember he said that the flow meter was calibrated at a pressure of 1030mbar or so, maybe that's the def.

Do you mind putting a note in the logbook with your plot, maybe as an answer to Oscar's entry: https://lblogbook.cern.ch/HEV/28

I'll merge your branch

For the leak,  it will pop up if you do the difference of volume between the positive and negative flow. I am not really good at thermodynamics, but I guess the flow of a leak depends on the pressure, so maybe there is a way to ling the P_aw in testchest (or the P_inhale), the extra volume seen in the inhale step vs the exhale one... Not sure what is the best approach

Thanks for the fast answer!

**Comment by cocov** [comment]
"I wanted to plot the two flows one against the other but I am struggling with the different number of points in the hev and tc datasets, so for the moment I've only pushed this." --> that will be solved by https://github.com/hev-sw/hev-analysis/issues/3 in the mean time if you need it you can une the script non_linear_calib.py (it might not have been there in the code you cloned but I added it later)

**Comment by gcavalle** [comment]
Yes, indeed the slopes of the flow at negative values are significantly different, that could indicate that is not due to some transient effects from the sensor itself. Tomorrow I will try to follow your suggestions to be more quantitative (thanks for the script!)
I will reply to Oscar's entry in the logbook

**Comment by cocov** [comment]
For usability, can you make the calibration part a function in utils? Ideally thi funtion would take as input data_hev, and inside open the excel file (maybe we can actually create a txt file out of it instead), and create a new column in data_hev name "Flow" which would be the calibrated data (so then we can call this function inside get_data.labview and we get the calib out of the way for the user).

I think the smearing (the fact that Dp is less "sharp" than the flow from testchest) is due to the fact the pressure change had to propagate along the 2m tubes and that the sensor has a response time or 5ms, maybe we can try convoluting the testchest flow with a 5 or 10ms gaussian just to see if they then look alike.
So the only "mystery" is why the integral of the negative part is smaller than the integral of the positive part. And that is most likely leak (I'll be at cern this afternoon to check).

**Comment by gcavalle** [comment]
I cleaned up a bit the code. I am still not sure about the units, but it will be easy to scale the flow from dp. I plotted the calibrated flow vs the testchest flow and it confirms what you see here https://lblogbook.cern.ch/HEV/32

**Comment by gcavalle** [comment]
Added Flow to data_hev dict

**Comment by gcavalle** [comment]
For the moment there is no conversion between the units of the flowmeter used to calibrate the dp sensor (that should be NL/h) and the units from the testchest flowmeter (for which I assumed the units are in mL/min).

**Comment by gcavalle** [comment]
I think I need some help to go forward, since I miss the meaning of most of the variables in the log files. Do you have their definition somewhere?

**Comment by cocov** [comment]
for the late answer:

for TestChest:

"Flow" | [mL/min] | the flow at the level of the lung
"Lung tidal volume" [mL] | the volume of the lung (varies between ~1000 and ~1400 ), often we call tidal volume the difference between min and max.
"p alveole" | [mbar] | the pressure at the alveola (ie compared to the airway pressure it has passed through a resitance)
"Airway pressure" | [mbar] | the airway pressure (which should be the same than P_inhale in the labview, except that it is measured at the other side of the tube)

the rest are more advanced, we can rediscuss them later


for labview:
(Mean) means it is 1ms mesure points averaged over 20ms 
P_regulated (Mean)| [mbar] | the pressure after the regulator , before the buffer 
P_buffer (Mean) | [mbar] | the pressure in the buffer  
P_inhale (Mean) | [mbar] | the pressure after the buffer in the tube connected to the patient
Untitled |?|? 
P_diff (Scaled) || used to be positive dp
P_diff_inv (Scaled) || used to be inverted negative dp
P_diff_inv (Scaled) 1| [mbar] | the differnetial pressure measurement (at the level of the mouthpiece)

**Comment by gcavalle** [comment]
I used your measurement from here: https://lblogbook.cern.ch/HEV/45
Just plotting the flows one vs the other, I reach an agreement if the flow from the testchest is in mL/s, and a factor 10 scaling was applied to the dp values. Does it make sense to you?

![fulltime](https://user-images.githubusercontent.com/63714577/79594852-1ca6a600-80de-11ea-9865-f36008fc985b.png)

![firstcycles](https://user-images.githubusercontent.com/63714577/79594872-23351d80-80de-11ea-9c60-998bcb66226c.png)

![secondcycles](https://user-images.githubusercontent.com/63714577/79594882-28926800-80de-11ea-9d30-655f6530ab42.png)
