### ISSUE TITLE
Interpolation utility

### ISSUE THREAD

**Issue by cocov** [hev-sw/hev-analysis#3]
# Description of the issue

the data we get from HEV (labview) and TestChest are timed and the time binning is not the same. In addition the timestamp of the testchest data is crap (look at the data file, it only record the second, so in the get_data.testchest I reconstruct a timestamp to the 10ms from the number of measurement up to the next second change, and in utils.get_dp_calibration I do a finer time alignement).

Ideally one would need to work with interpolated data in order to be able to use any timestamp.
I used in a few place some simple spline interpolation. They come with problems (there is no "smoothing" so if there is fluctuation it is propagated to the interpolated point, it does not take into account uncertainty ). Not big issue but one could play a bit.

# Task
1. Make a function in utils that allow easily to make the interpolation and access the value at any point (ie generalise what is here and there in the code such that we all use this function and are consistant)
2. Study a few settings like in https://docs.scipy.org/doc/scipy/reference/tutorial/interpolate.html (I remember having used InterpolatedUnivariateSpline and LSQUnivariateSpline in other project and it was not too bad, if I recall properly it had a bit more knob one could play with)

# Priority

TODO

**Comment by tevans1260** [comment]
Sorry in advance for the basic question:

if i look at the timestamps in 1403/hev_1c_1404.log vs 1403/tc_1c_1404.log from https://lblogbook.cern.ch/HEV/31, it would seem that they wouldn't overlap at all - indeed the time/pressure alignment falls over as there is a ~ half an hour delay between the two. The noleak data seems to line up on the other hand - suspiciously the start time(s) in the noleak and leak in the hev logs are identical - what am i missing here?

**Comment by cocov** [comment]
Yes... I might have screwed up. Maybe use the data from https://lblogbook.cern.ch/HEV/26 or https://lblogbook.cern.ch/HEV/23 (I think the one from 23 are in the dataset folder)

**Comment by tevans1260** [comment]
ahk no worries . 
I committed to utils/spline.py some little helper wrappers for smoothing / rebinning, altering the examples & utils/time_align.py to use them - not sure how close this is to what you had in mind .. should i go straight to the pull (merge?) request

**Comment by cocov** [comment]
yes push it in a branch like "tim_dev" , make a merge request and I'll do all the merge tonight.
Thanks!
