### ISSUE TITLE
Prepare the patient (simulator)

### ISSUE THREAD

**Issue by cocov** [hev-sw/hev-analysis#5]
# Description of the issue

In order to qualify the ventilator, NHS, WHO, etc... rely on a list of typical patient and the ventilator should be able to ventilate them. They can be loaded in the simulator and then we see if we manage to achieve ventilation

# Task

1. Find the list of patient to be tested (see table in MHRA, https://www.overleaf.com/4555812214zqnfnmstgbtk, in priciple it correspond to one of the ISO norm patient).
2. Check with @cocov how to create the config files in TestChest with the excel script (part of it is already done).
3. Create the patients and load them to the TestChest.

**Comment by ClaudiaBert** [comment]
Added the table in the doc, figure 16.
